package frc.robot;

import static frc.robot.Constants.CANIVORE_CAN_BUS_NAME;

public enum Ports {
    END_EFFECTOR(33, CANIVORE_CAN_BUS_NAME),
    ELEVATOR_MAIN(51, CANIVORE_CAN_BUS_NAME),
    ELEVATOR_FOLLOWER(50, CANIVORE_CAN_BUS_NAME),
    SWERVE_FLS(3, CANIVORE_CAN_BUS_NAME),
    SWERVE_FLD(4, CANIVORE_CAN_BUS_NAME),
    SWERVE_FLC(10, CANIVORE_CAN_BUS_NAME),
    SWERVE_FRS(5, CANIVORE_CAN_BUS_NAME),
    SWERVE_FRD(6, CANIVORE_CAN_BUS_NAME),
    SWERVE_FRC(11, CANIVORE_CAN_BUS_NAME),
    SWERVE_BRS(7, CANIVORE_CAN_BUS_NAME),
    SWERVE_BRD(8, CANIVORE_CAN_BUS_NAME),
    SWERVE_BRC(20, CANIVORE_CAN_BUS_NAME),
    SWERVE_BLS(1, CANIVORE_CAN_BUS_NAME),
    SWERVE_BLD(2, CANIVORE_CAN_BUS_NAME),
    SWERVE_BLC(0, CANIVORE_CAN_BUS_NAME),
    PIGEON(14, CANIVORE_CAN_BUS_NAME);

    public final int id;
    public final String bus;

    private Ports(int id, String bus) {
        this.id = id;
        this.bus = bus;
    }
}